apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-to-stage
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with Buildah,
    pushes it to a registry and deploys this image from manifests
  workspaces:
  - name: app-source
  tasks:
  - name: fetch-source
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: app-source
    params:
    - name: url
      value: https://github.com/vrutkovs/k8s-podhunt
    - name: revision
      value: tekton
  - name: manifests
    params:
      - name: SCRIPT
        value: |
          cd $(workspaces.manifest-dir.path)/manifests/overlays/stage
          NAMESPACE="$(context.pipelineRun.namespace)"
          echo "Namespace: ${NAMESPACE}"
          echo "Deploying commit $(tasks.fetch-source.results.commit)"
          oc apply -k .
    runAfter:
      - fetch-source
    taskRef:
      kind: ClusterTask
      name: openshift-client
    workspaces:
      - name: manifest-dir
        workspace: app-source
  - name: build-ui-src
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc start-build hunt-ui-src --wait
    runAfter:
      - manifests
  - name: build-ui-bin
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc start-build hunt-ui-bin --wait
    runAfter:
    - build-ui-src
  - name: build-backend
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc start-build hunt-backend-src --wait
    runAfter:
      - manifests
  - name: wait-for-ui-rollout
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc rollout status dc/hunt-ui
    runAfter:
    - build-ui-bin
  - name: wait-for-backend-rollout
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc rollout status dc/hunt-backend
    runAfter:
    - build-backend
