apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-to-stage
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with Buildah,
    pushes it to a registry and deploys this image from manifests
  workspaces:
  - name: app-source
  - name: dockerconfig-ws
  tasks:
  - name: build-ui-src
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc start-build hunt-ui-src --wait
  - name: build-ui-bin
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc start-build hunt-ui-bin --wait
    runAfter:
    - build-ui-src
  - name: build-backend-src
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc start-build hunt-backend-src --wait
  - name: build-backend-bin
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc start-build hunt-backend-bin --wait
    runAfter:
    - build-backend-src
  - name: wait-for-ui-rollout
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc rollout status dc/hunt-ui
    runAfter:
    - build-ui-bin
  - name: wait-for-backend-rollout
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc rollout status dc/hunt-backend
    runAfter:
    - build-backend-bin
