apiVersion: batch/v1
kind: Job
metadata:
  name: start-pipeline
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: pipeline
      containers:
      - name: start-pipeline
        image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        command:
        - bash
        - -c
        - |
          oc create -f - <<EOF
          apiVersion: tekton.dev/v1beta1
          kind: PipelineRun
          metadata:
            generateName: deploy-to-stage-
          spec:
            pipelineRef:
              name: deploy-to-stage
            timeout: 1h0m0s
          EOF
