apiVersion: batch/v1
kind: Job
metadata:
  name: start-pipeline
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: pipeline
      containers:
      - name: start-pipeline
        image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        command:
        - bash
        - -c
        - |
          oc create -f - <<EOF
          apiVersion: tekton.dev/v1beta1
          kind: PipelineRun
          metadata:
            generateName: deploy-to-stage-
          spec:
            pipelineRef:
              name: deploy-to-stage
            taskRunSpecs:
              - pipelineTaskName: push-ui-to-ghcr
                taskServiceAccountName: ghcr-service-account
              - pipelineTaskName: push-backend-to-ghcr
                taskServiceAccountName: ghcr-service-account
            timeout: 1h0m0s
            workspaces:
              - name: app-source
                volumeClaimTemplate:
                  metadata:
                    creationTimestamp: null
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 1Gi
                    volumeMode: Filesystem
              - name: images-url
                emptyDir: {}
          EOF
