apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hub-kubeconfig
  namespace: local-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: hub-kubeconfig
  data:
  - secretKey: kubeconfig
    remoteRef:
      key: /hub-cluster/kubeconfig
