kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: podhunt-global
  labels:
    app: podhunt
spec:
  host: devconf-vrutkovs-demo.devcluster.openshift.com
  to:
    kind: Service
    name: podhunt
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: 8080
