apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: podhunt-demo
spec:
  replicas: 3
  strategy:
    canary:
      antiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          weight: 50
      steps:
      - setWeight: 20
      - pause: {duration: 60}
      - setWeight: 40
      - pause: {duration: 60}
      - setWeight: 60
      - pause: {duration: 60}
      - setWeight: 80
      - pause: {duration: 60}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      deployment: hunt-backend
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hunt-backend
