apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-preview-from-pr
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with Buildah,
    pushes it to a registry and deploys this image from manifests
  params:
  - name: repo-url
    type: string
    default: https://github.com/vrutkovs/k8s-podhunt
  - name: repo-revision
    type: string
    default: main
  workspaces:
  - name: app-source
  tasks:
  - name: fetch-source
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: app-source
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.repo-revision)
  - name: manifests
    params:
      - name: SCRIPT
        value: |
          cd $(workspaces.manifest-dir.path)/manifests/overlays/dev
          NAMESPACE="$(context.pipelineRun.namespace)"
          echo "Namespace: ${NAMESPACE}"
          echo "Repository: $(params.repo-url)"
          echo "Commit: $(tasks.fetch-source.results.commit)"
          cat <<EOF >> kustomization.yaml
          patchesJson6902:
          - patch: |-
              - op: replace
                path: /spec/host
                value: duckhunt-${NAMESPACE}.apps.vrutkovs-dev.devcluster.openshift.com
            target:
              group: route.openshift.io
              kind: Route
              name: backend
              version: v1
          - patch: |-
              - op: replace
                path: /spec/host
                value: duckhunt-${NAMESPACE}.apps.vrutkovs-dev.devcluster.openshift.com
            target:
              group: route.openshift.io
              kind: Route
              name: ui
              version: v1
          - patch: |-
              - op: replace
                path: /spec/source/git/uri
                value: "$(params.repo-url)"
              - op: replace
                path: /spec/source/git/ref
                value: "$(tasks.fetch-source.results.commit)"
            target:
              group: build.openshift.io
              kind: BuildConfig
              name: hunt-backend-src
              version: v1
          EOF
          oc apply -k .
    runAfter:
      - fetch-source
    taskRef:
      kind: ClusterTask
      name: openshift-client
    workspaces:
      - name: manifest-dir
        workspace: app-source
  - name: build-ui-src
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc start-build hunt-ui-src --wait
    runAfter:
      - manifests
  - name: build-ui-bin
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc start-build hunt-ui-bin --wait
    runAfter:
    - build-ui-src
  - name: build-backend
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc start-build hunt-backend-src --wait
    runAfter:
      - manifests
  - name: wait-for-ui-rollout
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc rollout status dc/hunt-ui
    runAfter:
    - build-ui-bin
  - name: wait-for-backend-rollout
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: oc rollout status dc/hunt-backend
    runAfter:
    - build-backend
