---
apiVersion: v1
data:
  session_secret: Y2hhbmdlIG1lCg==
kind: Secret
metadata:
  name: grafana-proxy
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: ocp-injected-certs
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-proxy
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
rules:
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
---
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-proxy
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
roleRef:
  kind: ClusterRole
  name: grafana-proxy
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: grafana
---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: main
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  config:
    log:
      mode: "console"
      level: "warn"
    security:
      admin_user: kube:admin
      cookie_secure: True
    auth.anonymous:
      enabled: True
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.basic:
      enabled: True
    auth.proxy:
      enabled: True
      enable_login_token: True
      header_property: username
      header_name: X-Forwarded-User
  containers:
    - args:
        - '-provider=openshift'
        - '-pass-basic-auth=false'
        - '-https-address=:9091'
        - '-http-address='
        - '-email-domain=*'
        - '-upstream=http://localhost:3000'
        - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
        - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
        - '-tls-cert=/etc/tls/private/tls.crt'
        - '-tls-key=/etc/tls/private/tls.key'
        - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
        - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
        - '-openshift-service-account=grafana-serviceaccount'
        - '-openshift-ca=/etc/pki/tls/cert.pem'
        - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
        - '-openshift-ca=/etc/grafana-configmaps/ocp-injected-certs/ca-bundle.crt'
        - '-skip-auth-regex=^/metrics'
      image: 'quay.io/openshift/origin-oauth-proxy'
      name: grafana-proxy
      ports:
        - containerPort: 9091
          name: https
      resources: {}
      volumeMounts:
        - mountPath: /etc/tls/private
          name: secret-grafana-tls
          readOnly: false
        - mountPath: /etc/proxy/secrets
          name: secret-grafana-proxy
          readOnly: false
  secrets:
    - grafana-tls
    - grafana-proxy
  configMaps:
    - ocp-injected-certs
  service:
    ports:
      - name: https
        port: 9091
        protocol: TCP
        targetPort: https
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: grafana-tls
  ingress:
    enabled: True
    targetPort: https
    termination: reencrypt
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: grafana-tls
  client:
    preferService: True
  serviceAccount:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-access"}}'
  resources:
    limits:
      cpu: 2000m
      memory: 8000Mi
    requests:
      cpu: 100m
      memory: 200Mi
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana-access
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    service.beta.openshift.io/serving-cert-secret-name: grafana-tls
spec:
  host: grafana.apps.vrutkovs-demo.origin-gce.dev.openshift.com
  port:
    targetPort: https
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: grafana-service
    weight: 100
  wildcardPolicy: None
