apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: main
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  config:
    log:
      mode: "console"
      level: "warn"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.basic:
      enabled: True
    auth.proxy:
      enabled: True
      auto_sign_up: True
      header_name: X-Forwarded-User
    users:
      allow_sign_up: False
      auto_assign_org: True
      auto_assign_org_role: Editor
    security:
      admin_user: cluster-admin
      cookie_secure: True
  ingress:
    enabled: true
    tlsEnabled: true
