apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafanadatasource
  namespace: grafana-operator
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        # oc create token grafana-serviceaccount --duration=8760h -n grafana-operator
        httpHeaderValue1: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjdfdDF1X3dpZDFoT0dKYkZQc0VIc1dZckhydUJtLU01VnFwV3ZlaGNqQWcifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTcxODE5NTY4NCwiaWF0IjoxNjg2NjU5Njg0LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImdyYWZhbmEtb3BlcmF0b3IiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZ3JhZmFuYS1zZXJ2aWNlYWNjb3VudCIsInVpZCI6ImJlMjM3ZWViLTRiNGQtNDFiMi1hM2QzLWE5NGFkNmZhMGRhZiJ9fSwibmJmIjoxNjg2NjU5Njg0LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6Z3JhZmFuYS1vcGVyYXRvcjpncmFmYW5hLXNlcnZpY2VhY2NvdW50In0.fy5q6k1VrfPhltfZe__7yIrVNmOSKHT1G_-Ll3pdiVD56hNdz_NoxqpM0NKsBVkuRccuvreSCf6K1cRTc2mzGV1dxHGvf6QsxV64Ijr-XS7H7KlWmaupoljGmS65Xadb70GgzdK8yuUa6r217IjWWp7UgyGgPpP0ON1C_27pJQGsEaAPLaeDaqWDY215rklTt2_t1UHX_Ttihqsu4ZnWT_uo5LAaQxD0HfS-XVEeG5Wc4llPjP8Yv4l9dq_eQYAiuzAeopBt8PCbeg--YvVPbOc5oPylX40oSLMfBaNnVr0R7jCpvU75h0F9EzBepj5r5Z-Lgwqiq1giz7C280YTS1cyJHibID-30oy9h2rxLQn9CyKcPfS6U2-s4GNG_O8qa-0ZSxk12wcVof6v9arXYSVEql5OqRAcd-c-NkGRDLfYbyZBPQs0mc7EySXMWVSNynGl98NApysFcMJM5GN0Bvrfg63dbNt4ORsligPfvfckSaj-UYO4dEeEq3xHmD7SzpQFA-djiRcHD0rHFm21WTVi4no_I6uBB2nBtBspyDBdXG-a1ZOaknTTyewX9XSYB4CrxsMPiv61THiWDCwDLHrZt930_zgvTDX1U6Ot0kwwWWmmyvGdV2elBdhsltPTq8SEC0ua3QZoTFpBfjqAOdhdt_clDXBQDcBFs8FAi0Y'
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
  name: prometheus-grafanadatasource.yaml
