apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-prod
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: prod-cluster
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'workload-prod-{{name}}'
    spec:
      destination:
        namespace: workload
        server: '{{server}}'
      project: default
      source:
        path: 'manifests/overlays/{{name}}/'
        repoURL: https://github.com/vrutkovs/k8s-podhunt
        targetRevision: 0c390eb
        kustomize:
          images:
          - ghcr.io/vrutkovs/k8s-podhunt-ui:671d5be30ea2a095f772560f4bdc1f01315704e9
          - ghcr.io/vrutkovs/k8s-podhunt-backend:671d5be30ea2a095f772560f4bdc1f01315704e9
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Validate=false
          - Replace=false
          - PrunePropagationPolicy=background
