apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: argocd
spec:
  destination:
    namespace: openshift-kube-descheduler-operator
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/descheduler
    repoURL: 'https://github.com/vrutkovs/devconfcz-2023-demo'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
